name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: Run a one-line script
       run:  mvn sonar:sonar -Dsonar.host.url="http://172.16.0.53:9000" -Dsonar.login="admin" -Dsonar.password="Welcome5ggk" -Dsonar.projectKey=webapp -Dsonar.projectName=webapp

