on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: http://172.16.0.53:9000
        login: 6986f485119f5c4e22ab54d7346ecb82631fe01d
        projectBaseDir: ./target
        projectKey: MyWebApp
