on: push
name: Main Workflow
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarQube Scan
      uses: kitabisa/sonarqube-action@master
      with:
        host: http://172.16.0.53:9000
        login: admin
        password: Welcome5ggk
        projectBaseDir: ./target
        projectKey: MyWebApp
