name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - uses: actions/checkout@v2
     - name: Run a one-line script
       run:  mvn clean install

